### ISSUE TITLE
Position of mydaterangepicker below a label

### ISSUE THREAD

**Issue by yudigs17** [kekeh/mydaterangepicker#91]
![screen shot 2017-11-22 at 16 14 04](https://user-images.githubusercontent.com/33893864/33119016-3fad1478-cfa0-11e7-9ee6-8ac201295d4b.png)
Hi, anyone can help me on how to make the mydaterangepicker position below the label Date Created?

**Comment by yudigs17** [comment]
Hi,
Ok, i fixed the issue by applying css display: block to the element of mydaterangepicker.
Anyone has better solution to solve this?

**Comment by RoraxHan** [comment]
hello, how did you solve this issue with display:block attribute.
I didn't solve this problem

**Comment by yudigs17** [comment]
i did this in my css

#dateSales {
  display: block;
}

where datesSales is the name of the template variable in my html page.
